module.exports = {
  testEnvironment: "node",
  roots: ["<rootDir>", "<rootDir>/__tests__"],
  testMatch: ["**/*.test.js"],
  setupFiles: ["<rootDir>/jest.setup.js"],
  clearMocks: true,
  collectCoverageFrom: [
    "server.js",
    "helpers.js",
    "services/geo.js",
    "services/mapboxGeocode.js",
    "routes/fairs.js",
    "routes/shortlist.js",
    "lib/employerCandidates.js",
    "console.js",
    "resumeParser.js",
    "resumeTailorSimple.js",
    "patchApplier.js",
    "patchValidator.js",
    "lib/qaSessionMutations.js",
  ],
  coverageDirectory: "coverage",
  coverageReporters: ["text", "lcov"],
};
