module.exports = {
  testEnvironment: "node",
  roots: ["<rootDir>", "<rootDir>/__tests__"],
  testMatch: ["**/*.test.js"],
  setupFiles: ["<rootDir>/jest.setup.js"],
  clearMocks: true,
  collectCoverageFrom: [
    "server.js",
    "helpers.js",
    "console.js",
    "resumeParser.js",
    "resumeTailorSimple.js",
    "resumeTailorHelpers.js",
    "patchApplier.js",
    "patchValidator.js",
    "patchCache.js",
    "streamServerClient.js",
    "routes/**/*.js",
    "lib/**/*.js",
    "services/**/*.js",
    "middleware/**/*.js",
    "__tests__/testUtils.js",
    "jest.setup.js",
    "jestSetupConsole.js",
    "jestSetupEnv.js",
    "!**/node_modules/**",
  ],
  coverageDirectory: "coverage",
  coverageReporters: ["text", "lcov"],
};
