/**
 * Canonical interest tags (lowercase). Students may only select from this list.
 * Keep in sync with any employer-facing copy about searchable interests.
 */
export const ACCEPTED_INTEREST_TAGS: readonly string[] = [
  "accounting",
  "aerospace",
  "agriculture",
  "ai",
  "architecture",
  "biomedical",
  "biotechnology",
  "business analytics",
  "chemical engineering",
  "chemistry",
  "civil engineering",
  "cloud computing",
  "communications",
  "computer engineering",
  "computer science",
  "consulting",
  "construction",
  "consumer products",
  "cybersecurity",
  "data science",
  "design",
  "devops",
  "economics",
  "education",
  "electrical engineering",
  "energy",
  "entrepreneurship",
  "environmental",
  "finance",
  "government",
  "healthcare",
  "human resources",
  "industrial engineering",
  "insurance",
  "investment banking",
  "law",
  "logistics",
  "machine learning",
  "management",
  "manufacturing",
  "marketing",
  "materials science",
  "mechanical engineering",
  "nonprofit",
  "nursing",
  "operations",
  "pharmaceuticals",
  "physics",
  "policy",
  "product management",
  "project management",
  "public relations",
  "real estate",
  "research",
  "retail",
  "sales",
  "social impact",
  "software engineering",
  "sports",
  "supply chain",
  "sustainability",
  "teaching",
  "transportation",
  "ux",
  "venture capital",
  "web development",
].sort((a, b) => a.localeCompare(b))
